---
- name: Verify | wait for MySQL container to become healthy
  ansible.builtin.command:
    cmd: >-
      docker inspect --format='{{ '{{' }}.State.Health.Status{{ '}}' }}'
      {{ phpbb_mysql_container_name }}
  register: _phpbb_mysql_health
  until: _phpbb_mysql_health.stdout == "healthy"
  retries: "{{ phpbb_verify_healthcheck_retries }}"
  delay: "{{ phpbb_verify_healthcheck_delay }}"
  changed_when: false
  when: phpbb_verify_healthcheck | bool
  tags: molecule-notest

- name: Verify | wait for phpBB container to become healthy
  ansible.builtin.command:
    cmd: >-
      docker inspect --format='{{ '{{' }}.State.Health.Status{{ '}}' }}'
      {{ phpbb_container_name }}
  register: _phpbb_health
  until: _phpbb_health.stdout == "healthy"
  retries: "{{ phpbb_verify_healthcheck_retries }}"
  delay: "{{ phpbb_verify_healthcheck_delay }}"
  changed_when: false
  when: phpbb_verify_healthcheck | bool
  tags: molecule-notest
