---
- name: Restart phpbb
  community.docker.docker_compose_v2:
    project_src: "{{ phpbb_compose_dir }}"
    state: present
    services:
      - phpbb
    restart: true
  tags: molecule-notest

- name: Restart mysql
  community.docker.docker_compose_v2:
    project_src: "{{ phpbb_compose_dir }}"
    state: present
    services:
      - mysql
    restart: true
  tags: molecule-notest
